version: "3"

services:
  server:
    image: huhengbo1992/rss-reader:latest
    container_name: rss-reader
    restart: always
    ports:
      - "9898:8080"
    volumes:
      - "$PWD/config.json:/app/config.json"
